In [26]:
import numpy as np

import pandas as pd

data_set= pd.read_excel('sa.csv')

In [27]:

# print(data_set)

x= data_set.iloc[:,:-1].values  

# print(x)

y= data_set.iloc[:,3].values  

from sklearn.impute import SimpleImputer

 

# Create an instance of SimpleImputer with desired strategy (e.g., mean)

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

 

# Fit the imputer to the independent variables x

imputer.fit(x[:, 1:3])

 

# Transform and replace missing data with the calculated mean value

x[:, 1:3] = imputer.transform(x[:, 1:3])

# print(x)

 

from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer

 

# Create an instance of OneHotEncoder

onehot_encoder = OneHotEncoder()

 

# Encode the categorical feature without using LabelEncoder

x_encoded = onehot_encoder.fit_transform(x[:, 0].reshape(-1, 1)).toarray()

 

# Use ColumnTransformer to apply OneHotEncoder and keep other columns unchanged

column_transformer = ColumnTransformer(

    transformers=[('onehot', OneHotEncoder(), [0])],

    remainder='passthrough'

)

 

# Apply ColumnTransformer to the remaining columns

x = column_transformer.fit_transform(x)

print(x)

 

from sklearn.preprocessing import LabelEncoder

 

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

print(y)

 

from sklearn.model_selection import train_test_split  

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  

 

from sklearn.preprocessing import StandardScaler  

st_x= StandardScaler()  

x_train= st_x.fit_transform(x_train)

print(x_train)

x_test= st_x.transform(x_test)  

print(x_test)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
